In [1]:
# Theory part writing sooon

# Example Code

#### For neural network we require additional package tensorflow

__!pip install tensorflow__

In [5]:
!pip install tensorflow


[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
# importing required packages

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import tensorflow as tf
from tensorflow.keras.layers import Dense
# Dense: to add layers(hidden, output)
from tensorflow.keras import Sequential
# Sequential: to add layers in sequence, to initialize ann model i.e. initially random weight will be assigned

from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings('ignore')

In [9]:
# importing dataset

df = pd.read_csv("Datasets\\Churn_Modelling.csv")
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [13]:
# Exited is target column which is binary

# Hence the problem is binary classification

# given the customer details, bank want to predict whether customer will leave the bank or not.

In [15]:
# Not important columns
df.drop(columns=['RowNumber','CustomerId','Surname'], inplace=True)

In [17]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [21]:
df.isna().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [23]:
# data is good now

# We have to convert catagorical in to numrical

In [25]:
df = pd.get_dummies(data=df, columns=['Geography','Gender'],dtype=int)   # dtype=int will encoded values (0,1) rather than True, False
df.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1                 1   
1               1        112542.58       0                 0   
2               0        113931.57       1                 1   
3               0         93826.63       0                 1   
4               1         79084.10       0                 0   

   Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                  0                0              1            0  
1                  0                1              1            0  
2                  0                0              1            0  
3                  0                0              1            0  
4                  0                1              1            0

In [29]:
df.shape

(10000, 14)

## Model Building

In [32]:
df

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0                  1        101348.88       1                 1   
1                  1        112542.58       0                 0   
2                  0        113931.57       1                 1   
3                  0         93826.63       0                 1   
4                  1         79084.10       0                 0   
...              ...              ...     ...               ...   
9995               0         96270.64       0                 1   
9996               1        101699.77       0                 1   
9997               1         42085.58       1                 1   
9998               0         92888.52       1                 0   
9999               0         38190.78       0                 1   

      Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                     0                0              1            0  
1                     0                1              1            0  
2                     0                0              1            0  
3                     0                0              1            0  
4                     0                1              1            0  
...                 ...              ...            ...          ...  
9995                  0                0              0            1  
9996                  0                0              0            1  
9997                  0                0              1            0  
9998                  1                0              0            1  
9999                  0                0              1            0  

[10000 rows x 14 columns]

In [34]:
sc = StandardScaler() # don't perform standardization on target column
x = df.drop(columns=['Exited'])# exclude Exited column
y = df['Exited']

In [36]:
x = sc.fit_transform(x)
x

array([[-0.32622142,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.44003595,  0.19816383, -1.38753759, ...,  1.74273971,
         1.09598752, -1.09598752],
       [-1.53679418,  0.29351742,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.25683526,  0.29351742, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752]])

In [38]:
# we have x and y now, let's split data into train and test

xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.20, random_state=1)

In [40]:
xtrain

array([[-0.23310044, -0.94607926, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [-0.25379399, -0.94607926, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.39864885,  0.77028538,  0.34135195, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.22215769,  0.5795782 ,  1.37868567, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 0.12903671,  0.00745665,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.16371428,  0.29351742,  0.34135195, ..., -0.57380915,
        -0.91241915,  0.91241915]])

In [42]:
# create instance of Sequential class or initialize the model
model = Sequential()
# Sequential is a class in Keras that allows you to build ANN model layer-by-layer.
# create neurons in input, hidden and output layers and assign random weights to input
# In I/P layer 13 neurons will be there as there are 13 independent features

#Add hidden layer, randomly 10 neurons are added
model.add(Dense(units=10,activation='relu'))# as target is binary use relu activation
# Layers are added sequentially using the .add() method.
# Each layer receives input from the previous layer and passes output to the next one.

#Add output layer
model.add(Dense(units=1, activation='sigmoid'))# for binary classification use sigmoid activation in output layer

#Establish the connection between the layers
model.compile(optimizer = 'adadelta',loss='binary_crossentropy',metrics=['accuracy'])
# adadelta is gradient descent algorithm for weight updation which we have selected randomly. We will hypertune it afterwards
# binary_crossentropy: also called log_loss, finds erros, range is 0 to 1

#Fit the data, perform forward and back propagation
model.fit(xtrain,ytrain, epochs=100)
# epochs=100 means that the model will go through the entire xtrain and ytrain dataset 100 times during training.
# epoch: backward and forward propagation will be done for 100 times
# The number of batches per epoch = Total number of samples / Batch size (default is 32)
# 80% training data = 8000 samples. So Batches=8000/32 = 250
# Each batch is processed in sequence during each epoch,
# and after all 250 batches are processed, one epoch is complete.

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6015 - loss: 0.6697
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5934 - loss: 0.6765
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6023 - loss: 0.6675
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5881 - loss: 0.6858
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5918 - loss: 0.6752
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6000 - loss: 0.6785
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6059 - loss: 0.6730
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5987 - loss: 0.6788
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5983 - loss: 0.6709
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6039 - loss: 0.6712
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5988 - loss: 0.6705
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

In [44]:
# accuracy is not good and error is also high as hyperparameter tuning is not done
xtest

array([[-1.04014895,  0.77028538, -1.04175968, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 0.3049319 , -0.4693113 , -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [-1.23673768,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [-0.86425376, -0.4693113 ,  1.72446358, ...,  1.74273971,
        -0.91241915,  0.91241915],
       [-0.30552787, -0.85072567, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 0.0462625 ,  1.24705333,  1.37868567, ..., -0.57380915,
        -0.91241915,  0.91241915]])

In [46]:
ypred = model.predict(xtest)
ypred # in dataset target column values are 0 or 1, but here output is a continuous number
# because in output layer activation function is sigmoid. It gives you o/p in terms of probability
# In sigmoid if probability is > 0.5 it gives you 1 and if probability < 0 it should give 0

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


array([[0.31160796],
       [0.5392981 ],
       [0.14555968],
       ...,
       [0.38793883],
       [0.12270932],
       [0.54538035]], dtype=float32)

In [48]:
ypred

array([[0.31160796],
       [0.5392981 ],
       [0.14555968],
       ...,
       [0.38793883],
       [0.12270932],
       [0.54538035]], dtype=float32)

In [50]:
print(classification_report(ytest,ypred))   # Will give error as ypred is continuous

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [52]:
ypred = ypred > 0.5
ypred

array([[False],
       [ True],
       [False],
       ...,
       [False],
       [False],
       [ True]])

In [54]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.80      0.85      0.82      1585
           1       0.22      0.17      0.19       415

    accuracy                           0.71      2000
   macro avg       0.51      0.51      0.51      2000
weighted avg       0.68      0.71      0.69      2000



In [56]:
# Now we will try to tune the model to get max accuracy


# For now we will try tune optimizer only and not any other param for understanding

## Hyperparameter Tuning

In [60]:
# For this we need keras-tuner

!pip install -U keras-tuner


[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [62]:
import keras_tuner as kt

In [64]:
# tuning for optimizer(adam,rmsprop or sgd:stochastic gradient descent) only
def optimizer_selection(hp):
    # hp (HyperParameters) is an object used to define search spaces for the hyperparameters you want to tune.
    # This allows the Keras Tuner to explore different values for the hyperparameters
    # and find the best ones during the search.

    #create instance of sequential class
    model = Sequential()
    #Add hidden layer
    model.add(Dense(units=10, activation='relu'))
    #Add output layer
    model.add(Dense(units=1, activation='sigmoid'))
    #Optimizer selection
    optim = hp.Choice('optimizer', values = ['sgd','adam','rmsprop']) #value of optimizer is categorical so use choice()function else use hp.Int()
    model.compile(optimizer=optim, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return model

In [66]:
# similar to GridSearchCV() we will use here RandomSearch()
tuner = kt.RandomSearch(
    optimizer_selection,# model name-here Sequential() class is our model
    objective='val_accuracy', # increase accuracy of test data i.e. validation test accuracy or minimize 'val_loss'
    max_trials=3 # for each optimizer take 3 trials: for sgd-3 trials, for adam-3 trials, for rmsprop-3 trials
    # can select 3 to 10 or 20 for larger problems
)

In [68]:
tuner.search(xtrain,ytrain, epochs = 3, validation_data = (xtest,ytest))
# tuner.search() is equivalent to grid.fit()
# When we call tuner.search(), we are not directly calling the hyper() function.
# Instead, Keras Tuner automatically calls hyper()
# and passes the hp object to it during the search.
# We don’t manually pass hp as an argument because Keras Tuner handles it behind the scenes.

# epochs should be same as max_trials so 3 is selected
# validation_data: pass test data

Trial 3 Complete [00h 00m 03s]
val_accuracy: 0.8015000224113464

Best val_accuracy So Far: 0.8190000057220459
Total elapsed time: 00h 00m 10s


In [70]:
tuner.get_best_hyperparameters()[0].values # as per performance all optimizers are stored in an array
# we want high accuracy optimizer present at index 0 location

{'optimizer': 'rmsprop'}

In [72]:
model = tuner.get_best_models(num_models=1)[0] # get best model: rmsprop
model.fit(xtrain,ytrain, epochs = 100, validation_data = (xtest,ytest))

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8190 - loss: 0.4309 - val_accuracy: 0.8235 - val_loss: 0.4105
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8253 - loss: 0.4202 - val_accuracy: 0.8255 - val_loss: 0.4051
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8314 - loss: 0.4111 - val_accuracy: 0.8315 - val_loss: 0.4002
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8389 - loss: 0.4010 - val_accuracy: 0.8350 - val_loss: 0.3943
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8350 - loss: 0.4069 - val_accuracy: 0.8415 - val_loss: 0.3889
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8417 - loss: 0.3977 - val_accuracy: 0.8470 - val_loss: 0.3827
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8502 - loss: 0.3785 - val_accuracy: 0.8510 - val_loss: 0.3753
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8571 - loss: 0.3648 - val_accu

In [78]:
model.evaluate(xtrain,ytrain)    # 86.10 % training accuracy

250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8636 - loss: 0.3356


[0.3337854743003845, 0.8610000014305115]

In [84]:
model.evaluate(xtest,ytest)    # 86.54 % testing accuracy

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8625 - loss: 0.3436


[0.33413493633270264, 0.8654999732971191]

# Regression

In [109]:
df = pd.read_csv("Datasets\\Price.csv")
df

price     feature1     feature2
0    461.527929   999.787558   999.766096
1    548.130012   998.861615  1001.042403
2    410.297162  1000.070267   998.844015
3    540.382220   999.952251  1000.440940
4    546.024553  1000.446011  1000.338531
..          ...          ...          ...
995  476.526078  1000.018988   999.672732
996  457.313186   998.855379  1000.020026
997  456.720993  1001.451646   998.847605
998  403.315576  1000.771023   998.562851
999  599.367094   999.232244  1001.451407

[1000 rows x 3 columns]

In [111]:
x = df.iloc[:,1:]
y = df['price']

In [113]:
x = sc.fit_transform(x)
x

array([[-0.23277509, -0.22551031],
       [-1.18389307,  1.12100979],
       [ 0.05762098, -1.19831827],
       ...,
       [ 1.47655818, -1.19452982],
       [ 0.77742978, -1.49494959],
       [-0.80318737,  1.55251428]])

In [115]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2, random_state=1)

In [117]:
ann = Sequential()

ann.add(Dense(units=30, activation='relu'))# hidden layer1
ann.add(Dense(units=20, activation='relu'))# hidden layer2

ann.add(Dense(units=1))# output layer.
#In Regression task no activation function is required in output layer as we don't have to convert price to 0 or 1

ann.compile(optimizer='adam',loss = 'mse')

ann.fit(xtrain,ytrain, epochs = 100, validation_data = (xtest,ytest))

Epoch 1/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 258351.1875 - val_loss: 262551.9062
Epoch 2/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 253468.5312 - val_loss: 261918.9375
Epoch 3/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 251775.9375 - val_loss: 260926.2344
Epoch 4/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 249485.9219 - val_loss: 259390.7656
Epoch 5/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 250070.4531 - val_loss: 257091.9844
Epoch 6/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 247431.3281 - val_loss: 253757.8594
Epoch 7/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 246510.0781 - val_loss: 249047.6875
Epoch 8/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 240411.4062 - val_loss: 242737.7656
Epoch 9/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 235906.9062 - val_loss: 234496.4062
Epoch 10/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 221083.2500 - val_loss: 224253.7188
Epoch 11/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/s

In [119]:
yp = ann.predict(xtest)
yp

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


array([[476.47766],
       [529.0957 ],
       [493.87207],
       [533.63605],
       [656.72766],
       [343.48688],
       [352.42798],
       [376.50198],
       [719.9009 ],
       [496.3824 ],
       [473.60904],
       [510.1005 ],
       [495.91455],
       [363.75555],
       [551.26196],
       [489.60873],
       [578.75385],
       [552.1021 ],
       [483.44385],
       [500.55286],
       [465.95398],
       [596.3341 ],
       [442.07132],
       [579.97485],
       [427.18585],
       [524.341  ],
       [383.92114],
       [497.17914],
       [546.1193 ],
       [356.1774 ],
       [436.97485],
       [639.8865 ],
       [562.421  ],
       [539.5328 ],
       [612.5668 ],
       [541.6356 ],
       [406.03375],
       [576.8827 ],
       [562.7456 ],
       [514.0549 ],
       [422.43695],
       [732.19324],
       [527.355  ],
       [534.83905],
       [509.46442],
       [452.0888 ],
       [519.3789 ],
       [525.1778 ],
       [592.02356],
       [468.79   ],


In [121]:
from sklearn.metrics import r2_score # accuracy metric for regression task is r squared

In [123]:
r2_score(ytest,yp)

0.9698558310411356

In [125]:
# 96.98 % accuracy